services:
  # Service de base de données PostgreSQL
  - type: pserv
    name: lon-db
    plan: starter
    env: image
    image:
      url: postgres:16-alpine
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: lon_db

  # Service backend Django
  - type: web
    name: lon-backend
    env: docker
    rootDir: lon
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /api/health/
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: lon-db
          envVarKey: POSTGRES_URL
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.render.com,localhost"
    
  # Service frontend
  - type: web
    name: lon-frontend
    env: node
    buildCommand: cd lon_front && npm install && npm run build
    startCommand: cd lon_front && npx serve -s dist -l $PORT
    plan: starter
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: lon-backend
          property: url
