name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lon_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd lon
        pip install -r test-requirements.txt
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'stable'
        
    - name: Verify Chrome and ChromeDriver
      run: |
        google-chrome --version
        python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
      env:
        WDM_LOG_LEVEL: '0'
    
    - name: Run migrations
      working-directory: lon
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/lon_test_db
        DEBUG: '1'
        SECRET_KEY: 'test_key_for_running_tests'
        DJANGO_SETTINGS_MODULE: 'lon.settings_ci'
      run: |
        # Vérifier l'état de la base de données
        echo "Vérification de la base de données..."
        PGPASSWORD=postgres psql -h localhost -U postgres -c '\l' lon_test_db || echo "Base de données non disponible"
        
        # Vérifier si accounts_user existe déjà
        echo "Vérification de la table accounts_user..."
        PGPASSWORD=postgres psql -h localhost -U postgres -d lon_test_db -c "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'accounts_user');" || echo "Erreur lors de la vérification de accounts_user"
        
        # 1. Forcer le reset de la base de données
        echo "Réinitialisation de la base de données..."
        PGPASSWORD=postgres psql -h localhost -U postgres -c "DROP DATABASE IF EXISTS lon_test_db;"
        PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE lon_test_db;"
        
        # 2. Generate initial migrations avec le module auth d'abord
        echo "Génération des migrations initiales..."
        python manage.py makemigrations auth
        
        # 3. Generate migrations pour accounts (qui contient le modèle User)
        echo "Génération des migrations pour accounts..."
        python manage.py makemigrations accounts
        
        # 4. Generate migrations pour les autres apps
        echo "Génération des autres migrations..."
        python manage.py makemigrations
        
        # 5. Migrate auth et contenttypes d'abord (dépendances de User)
        echo "Migration des apps de base..."
        python manage.py migrate auth
        python manage.py migrate contenttypes
        
        # 6. Migrate accounts avec --fake-initial pour éviter les conflits
        echo "Migration de l'app accounts..."
        python manage.py migrate accounts --fake-initial || python manage.py migrate accounts
        
        # 7. Migrate tout le reste
        echo "Migration des autres apps..."
        python manage.py migrate
        
        # 8. Vérifier que accounts_user existe maintenant
        echo "Vérification finale de accounts_user..."
        PGPASSWORD=postgres psql -h localhost -U postgres -d lon_test_db -c "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'accounts_user');"
    
    - name: Run backend unit tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/lon_test_db
        DEBUG: '1'
        SECRET_KEY: 'test_key_for_running_tests'
        DJANGO_SETTINGS_MODULE: 'lon.settings_ci'
      run: |
        cd lon
        pytest projects/tests.py tasks/tests.py -v
    
    - name: Run database tests separately
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/lon_test_db
        DEBUG: '1'
        SECRET_KEY: 'test_key_for_running_tests'
        DJANGO_SETTINGS_MODULE: 'lon.settings_ci'
      run: |
        cd lon
        pytest api/tests.py::DatabaseConnectionTest -v
    
    - name: Create admin user for tests
      working-directory: lon
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/lon_test_db
        DJANGO_SETTINGS_MODULE: 'lon.settings_ci'
      run: |
        python manage.py shell -c "from accounts.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')" || echo "Erreur lors de la création de l'utilisateur"
        
        # Vérifier que l'utilisateur a bien été créé
        echo "Vérification de l'utilisateur admin..."
        python manage.py shell -c "from accounts.models import User; print(f'Utilisateur admin existe: {User.objects.filter(username=\"admin\").exists()}')"
        
        # Vérifier directement dans la base de données
        echo "Vérification directe dans la base de données..."
        PGPASSWORD=postgres psql -h localhost -U postgres -d lon_test_db -c "SELECT username FROM accounts_user WHERE username='admin';"
    
    - name: Start backend server for e2e tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/lon_test_db
        DEBUG: '1'
        SECRET_KEY: 'test_key_for_running_tests'
        DJANGO_SETTINGS_MODULE: 'lon.settings_ci'
        ALLOWED_HOSTS: 'localhost,127.0.0.1'
      run: |
        cd lon
        python manage.py runserver &
        # Attendre que le serveur soit prêt
        sleep 5
      
    - name: Build and start frontend
      run: |
        cd lon_front
        npm install
        npm run build
        
    - name: Install Nginx
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx
        
    - name: Configure Nginx for frontend
      run: |
        sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF
        server {
            listen 80;
            server_name localhost;
            
            root $(pwd)/lon_front/dist;
            index index.html;
            
            location / {
                try_files \$uri \$uri/ /index.html;
            }
        }
        EOF'
        sudo systemctl restart nginx
        
    - name: Run API tests
      working-directory: lon
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/lon_test_db
        DJANGO_SETTINGS_MODULE: 'lon.settings_ci'
      run: |
        python -m pytest api/tests.py -v

    - name: Run PostgreSQL connection tests
      working-directory: lon
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/lon_test_db
        DJANGO_SETTINGS_MODULE: 'lon.settings_ci'
      run: |
        python -m pytest api/tests.py::DatabaseConnectionTest -v

    - name: Run e2e tests
      working-directory: lon
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/lon_test_db
        DJANGO_SETTINGS_MODULE: 'lon.settings_ci'
        FRONTEND_URL: 'http://localhost:80'
        API_URL: 'http://localhost:8000/api'
      run: |
        python -m pytest e2e_tests/test_frontend_backend_ci.py -v
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pytest-results
        path: lon/pytest-report.xml 